// Code generated by mockery v2.53.4. DO NOT EDIT.

package am

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRawMessagePublisher is an autogenerated mock type for the RawMessagePublisher type
type MockRawMessagePublisher[T interface{}] struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, topicName, v
func (_m *MockRawMessagePublisher[T]) Publish(ctx context.Context, topicName string, v RawMessage) error {
	ret := _m.Called(ctx, topicName, v)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, RawMessage) error); ok {
		r0 = rf(ctx, topicName, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRawMessagePublisher creates a new instance of MockRawMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessagePublisher[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessagePublisher[T] {
	mock := &MockRawMessagePublisher[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
