// Code generated by mockery v2.53.4. DO NOT EDIT.

package am

import mock "github.com/stretchr/testify/mock"

// MockRawMessageSubscriber is an autogenerated mock type for the RawMessageSubscriber type
type MockRawMessageSubscriber[A AckableMessage] struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: topicName, handler, options
func (_m *MockRawMessageSubscriber[A]) Subscribe(topicName string, handler MessageHandler[AckableRawMessage], options ...SubscriberOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, topicName, handler)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, MessageHandler[AckableRawMessage], ...SubscriberOption) error); ok {
		r0 = rf(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unsubscribe provides a mock function with no fields
func (_m *MockRawMessageSubscriber[A]) Unsubscribe() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRawMessageSubscriber creates a new instance of MockRawMessageSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessageSubscriber[A AckableMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessageSubscriber[A] {
	mock := &MockRawMessageSubscriber[A]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
