// Code generated by mockery v2.53.4. DO NOT EDIT.

package am

import mock "github.com/stretchr/testify/mock"

// MockMessageSubscriber is an autogenerated mock type for the MessageSubscriber type
type MockMessageSubscriber[A AckableMessage] struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: topicName, handler, options
func (_m *MockMessageSubscriber[A]) Subscribe(topicName string, handler MessageHandler[A], options ...SubscriberOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, topicName, handler)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, MessageHandler[A], ...SubscriberOption) error); ok {
		r0 = rf(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMessageSubscriber creates a new instance of MockMessageSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSubscriber[A AckableMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSubscriber[A] {
	mock := &MockMessageSubscriber[A]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
