// Code generated by mockery v2.53.4. DO NOT EDIT.

package am

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventMessageHandler is an autogenerated mock type for the EventMessageHandler type
type MockEventMessageHandler[I AckableMessage] struct {
	mock.Mock
}

// HandleMessage provides a mock function with given fields: ctx, msg
func (_m *MockEventMessageHandler[I]) HandleMessage(ctx context.Context, msg EventMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, EventMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEventMessageHandler creates a new instance of MockEventMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventMessageHandler[I AckableMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventMessageHandler[I] {
	mock := &MockEventMessageHandler[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
