#!/bin/sh

set -e

if [ "$DEBUG" = "true" ]; then
  echo "Starting with Delve debugger..."
  exec /go/bin/dlv exec /mallbots/monolith --headless --listen=:40000 --api-version=2 --accept-multiclient
else
  echo "Starting application normally..."
  exec /mallbots/monolith
fi
